<?php
declare(strict_types = 1);

class Car {

    public static int $numOfWheel = 4 ;
    public static int $numOfDoors = 4;


    public static function carDetails() : void
    {
        echo "Number of Wheels: ".self::$numOfWheel.'<br/>';
        echo "Number of Doors: ".self::$numOfDoors.'<br/>';
    }
}

class Truck extends Car {

    private static int $cargoLength = 20;

    public static function details() :void
    {
        parent::carDetails(); // TODO: Change the autogenerated stub
        echo "Cargo Length: ". self::$cargoLength;
    }

}

$car= new Car();
$car::carDetails();
echo '===============<br/>';
$truck = new Truck();
$truck::details();
